"""
Django settings for progress project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ch*h*hulewg^z43q4ywb#nrl8i!lwg#1y!*0lo#ju+jfa@*i4_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'attendance',
    'TTU_SYSTEM',
    'home',
    'home1',
    'crispy_forms',
    'rolepermissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'progress.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'progress.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'progress.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Addis_Ababa'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/TTU_SYSTEM/lecturer/lec_login/'

LOGIN_REDIRECT_URL = 'TTU_SYSTEM:login_success'



LOGIN_EXEMPT_URLS = (
    'TTU_SYSTEM/student/create_profile',
    'TTU_SYSTEM/lecturer/create_profile'
    'TTU_SYSTEM:user_profile_with_pk',
    'TTU_SYSTEM:lec_profile_with_pk',
    'TTU_SYSTEM/student/login/',
    'TTU_SYSTEM/student/logout',
    'TTU_SYSTEM/student/user_profileform',
    'TTU_SYSTEM/student/register',
    'TTU_SYSTEM/student/reset-password',
    'TTU_SYSTEM/student/reset-password/done/',
    'TTU_SYSTEM/student/reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>,+)',
    'TTU_SYSTEM/student/reset-password/complete/',
    'TTU_SYSTEM/lecturer/lec_profileform',
    'TTU_SYSTEM/lecturer/lec_register',
    'TTU_SYSTEM/lecturer/logout',
    'TTU_SYSTEM/lecturer/reset-password',
    'TTU_SYSTEM/lecturer/reset-password/done/',
    'TTU_SYSTEM/lecturer/reset-password/confirm/(<uidb64>[0-9A-Za-z]+)-(<token>,+)',
    'TTU_SYSTEM/lecturer/reset-password/complete/',
)

MEDIA_ROOT =  os.path.join(BASE_DIR, '/media/','/TTU_SYSTEM/media/')
MEDIA_URL = '/media/'

EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025

AUTH_USER_MODEL = 'TTU_SYSTEM.CustomUser'

CRISPY_TEMPLATE_PACK = 'uni_form'